# Generated by Django 4.1.6 on 2023-02-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='eventgamer_gamer', through='levelupapi.EventGamer', to='levelupapi.gamer'),
        ),
    ]
